# Generated by Django 3.2.8 on 2021-10-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='Anonymous', editable=False)),
                ('command', models.CharField(max_length=100)),
                ('response', models.TextField(editable=False)),
                ('cwd', models.TextField(default='/', editable=False)),
            ],
        ),
    ]
