# Generated by Django 3.2.8 on 2021-10-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shell',
            name='user',
            field=models.TextField(default='Anonymous', editable=False),
        ),
    ]
