# Generated by Django 3.2.8 on 2021-10-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0002_rename_name_shell_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shell',
            name='response',
            field=models.TextField(editable=False),
        ),
    ]
